/* openal_patch.c -- openal redirection
 *
 * Copyright (C) 2023 Andy Nguyen
 *
 * This software may be modified and distributed under the terms
 * of the MIT license.  See the LICENSE file for details.
 */

#include <stdio.h>
#include <string.h>

#define AL_ALEXT_PROTOTYPES
#include <AL/alext.h>
#include <AL/efx.h>

#include "main.h"
#include "so_util.h"

void patch_openal(void) {
  hook_addr(so_symbol(&conduit_mod, "alAuxiliaryEffectSlotf"), (uintptr_t)&alAuxiliaryEffectSlotf);
  hook_addr(so_symbol(&conduit_mod, "alAuxiliaryEffectSlotfv"), (uintptr_t)&alAuxiliaryEffectSlotfv);
  hook_addr(so_symbol(&conduit_mod, "alAuxiliaryEffectSloti"), (uintptr_t)&alAuxiliaryEffectSloti);
  hook_addr(so_symbol(&conduit_mod, "alAuxiliaryEffectSlotiv"), (uintptr_t)&alAuxiliaryEffectSlotiv);
  hook_addr(so_symbol(&conduit_mod, "alBuffer3f"), (uintptr_t)&alBuffer3f);
  hook_addr(so_symbol(&conduit_mod, "alBuffer3i"), (uintptr_t)&alBuffer3i);
  hook_addr(so_symbol(&conduit_mod, "alBufferData"), (uintptr_t)&alBufferData);
  hook_addr(so_symbol(&conduit_mod, "alBufferf"), (uintptr_t)&alBufferf);
  hook_addr(so_symbol(&conduit_mod, "alBufferfv"), (uintptr_t)&alBufferfv);
  hook_addr(so_symbol(&conduit_mod, "alBufferi"), (uintptr_t)&alBufferi);
  hook_addr(so_symbol(&conduit_mod, "alBufferiv"), (uintptr_t)&alBufferiv);
  hook_addr(so_symbol(&conduit_mod, "alDeleteAuxiliaryEffectSlots"), (uintptr_t)&alDeleteAuxiliaryEffectSlots);
  hook_addr(so_symbol(&conduit_mod, "alDeleteBuffers"), (uintptr_t)&alDeleteBuffers);
  hook_addr(so_symbol(&conduit_mod, "alDeleteEffects"), (uintptr_t)&alDeleteEffects);
  hook_addr(so_symbol(&conduit_mod, "alDeleteFilters"), (uintptr_t)&alDeleteFilters);
  hook_addr(so_symbol(&conduit_mod, "alDeleteSources"), (uintptr_t)&alDeleteSources);
  hook_addr(so_symbol(&conduit_mod, "alDisable"), (uintptr_t)&alDisable);
  hook_addr(so_symbol(&conduit_mod, "alDistanceModel"), (uintptr_t)&alDistanceModel);
  hook_addr(so_symbol(&conduit_mod, "alDopplerFactor"), (uintptr_t)&alDopplerFactor);
  hook_addr(so_symbol(&conduit_mod, "alDopplerVelocity"), (uintptr_t)&alDopplerVelocity);
  hook_addr(so_symbol(&conduit_mod, "alEffectf"), (uintptr_t)&alEffectf);
  hook_addr(so_symbol(&conduit_mod, "alEffectfv"), (uintptr_t)&alEffectfv);
  hook_addr(so_symbol(&conduit_mod, "alEffecti"), (uintptr_t)&alEffecti);
  hook_addr(so_symbol(&conduit_mod, "alEffectiv"), (uintptr_t)&alEffectiv);
  hook_addr(so_symbol(&conduit_mod, "alEnable"), (uintptr_t)&alEnable);
  hook_addr(so_symbol(&conduit_mod, "alFilterf"), (uintptr_t)&alFilterf);
  hook_addr(so_symbol(&conduit_mod, "alFilterfv"), (uintptr_t)&alFilterfv);
  hook_addr(so_symbol(&conduit_mod, "alFilteri"), (uintptr_t)&alFilteri);
  hook_addr(so_symbol(&conduit_mod, "alFilteriv"), (uintptr_t)&alFilteriv);
  hook_addr(so_symbol(&conduit_mod, "alGenAuxiliaryEffectSlots"), (uintptr_t)&alGenAuxiliaryEffectSlots);
  hook_addr(so_symbol(&conduit_mod, "alGenBuffers"), (uintptr_t)&alGenBuffers);
  hook_addr(so_symbol(&conduit_mod, "alGenEffects"), (uintptr_t)&alGenEffects);
  hook_addr(so_symbol(&conduit_mod, "alGenFilters"), (uintptr_t)&alGenFilters);
  hook_addr(so_symbol(&conduit_mod, "alGenSources"), (uintptr_t)&alGenSources);
  hook_addr(so_symbol(&conduit_mod, "alGetAuxiliaryEffectSlotf"), (uintptr_t)&alGetAuxiliaryEffectSlotf);
  hook_addr(so_symbol(&conduit_mod, "alGetAuxiliaryEffectSlotfv"), (uintptr_t)&alGetAuxiliaryEffectSlotfv);
  hook_addr(so_symbol(&conduit_mod, "alGetAuxiliaryEffectSloti"), (uintptr_t)&alGetAuxiliaryEffectSloti);
  hook_addr(so_symbol(&conduit_mod, "alGetAuxiliaryEffectSlotiv"), (uintptr_t)&alGetAuxiliaryEffectSlotiv);
  hook_addr(so_symbol(&conduit_mod, "alGetBoolean"), (uintptr_t)&alGetBoolean);
  hook_addr(so_symbol(&conduit_mod, "alGetBooleanv"), (uintptr_t)&alGetBooleanv);
  hook_addr(so_symbol(&conduit_mod, "alGetBuffer3f"), (uintptr_t)&alGetBuffer3f);
  hook_addr(so_symbol(&conduit_mod, "alGetBuffer3i"), (uintptr_t)&alGetBuffer3i);
  hook_addr(so_symbol(&conduit_mod, "alGetBufferf"), (uintptr_t)&alGetBufferf);
  hook_addr(so_symbol(&conduit_mod, "alGetBufferfv"), (uintptr_t)&alGetBufferfv);
  hook_addr(so_symbol(&conduit_mod, "alGetBufferi"), (uintptr_t)&alGetBufferi);
  hook_addr(so_symbol(&conduit_mod, "alGetBufferiv"), (uintptr_t)&alGetBufferiv);
  hook_addr(so_symbol(&conduit_mod, "alGetDouble"), (uintptr_t)&alGetDouble);
  hook_addr(so_symbol(&conduit_mod, "alGetDoublev"), (uintptr_t)&alGetDoublev);
  hook_addr(so_symbol(&conduit_mod, "alGetEffectf"), (uintptr_t)&alGetEffectf);
  hook_addr(so_symbol(&conduit_mod, "alGetEffectfv"), (uintptr_t)&alGetEffectfv);
  hook_addr(so_symbol(&conduit_mod, "alGetEffecti"), (uintptr_t)&alGetEffecti);
  hook_addr(so_symbol(&conduit_mod, "alGetEffectiv"), (uintptr_t)&alGetEffectiv);
  hook_addr(so_symbol(&conduit_mod, "alGetEnumValue"), (uintptr_t)&alGetEnumValue);
  hook_addr(so_symbol(&conduit_mod, "alGetError"), (uintptr_t)&alGetError);
  hook_addr(so_symbol(&conduit_mod, "alGetFilterf"), (uintptr_t)&alGetFilterf);
  hook_addr(so_symbol(&conduit_mod, "alGetFilterfv"), (uintptr_t)&alGetFilterfv);
  hook_addr(so_symbol(&conduit_mod, "alGetFilteri"), (uintptr_t)&alGetFilteri);
  hook_addr(so_symbol(&conduit_mod, "alGetFilteriv"), (uintptr_t)&alGetFilteriv);
  hook_addr(so_symbol(&conduit_mod, "alGetFloat"), (uintptr_t)&alGetFloat);
  hook_addr(so_symbol(&conduit_mod, "alGetFloatv"), (uintptr_t)&alGetFloatv);
  hook_addr(so_symbol(&conduit_mod, "alGetInteger"), (uintptr_t)&alGetInteger);
  hook_addr(so_symbol(&conduit_mod, "alGetIntegerv"), (uintptr_t)&alGetIntegerv);
  hook_addr(so_symbol(&conduit_mod, "alGetListener3f"), (uintptr_t)&alGetListener3f);
  hook_addr(so_symbol(&conduit_mod, "alGetListener3i"), (uintptr_t)&alGetListener3i);
  hook_addr(so_symbol(&conduit_mod, "alGetListenerf"), (uintptr_t)&alGetListenerf);
  hook_addr(so_symbol(&conduit_mod, "alGetListenerfv"), (uintptr_t)&alGetListenerfv);
  hook_addr(so_symbol(&conduit_mod, "alGetListeneri"), (uintptr_t)&alGetListeneri);
  hook_addr(so_symbol(&conduit_mod, "alGetListeneriv"), (uintptr_t)&alGetListeneriv);
  hook_addr(so_symbol(&conduit_mod, "alGetProcAddress"), (uintptr_t)&alGetProcAddress);
  hook_addr(so_symbol(&conduit_mod, "alGetSource3f"), (uintptr_t)&alGetSource3f);
  hook_addr(so_symbol(&conduit_mod, "alGetSource3i"), (uintptr_t)&alGetSource3i);
  hook_addr(so_symbol(&conduit_mod, "alGetSourcef"), (uintptr_t)&alGetSourcef);
  hook_addr(so_symbol(&conduit_mod, "alGetSourcefv"), (uintptr_t)&alGetSourcefv);
  hook_addr(so_symbol(&conduit_mod, "alGetSourcei"), (uintptr_t)&alGetSourcei);
  hook_addr(so_symbol(&conduit_mod, "alGetSourceiv"), (uintptr_t)&alGetSourceiv);
  hook_addr(so_symbol(&conduit_mod, "alGetString"), (uintptr_t)&alGetString);
  hook_addr(so_symbol(&conduit_mod, "alIsAuxiliaryEffectSlot"), (uintptr_t)&alIsAuxiliaryEffectSlot);
  hook_addr(so_symbol(&conduit_mod, "alIsBuffer"), (uintptr_t)&alIsBuffer);
  hook_addr(so_symbol(&conduit_mod, "alIsEffect"), (uintptr_t)&alIsEffect);
  hook_addr(so_symbol(&conduit_mod, "alIsEnabled"), (uintptr_t)&alIsEnabled);
  hook_addr(so_symbol(&conduit_mod, "alIsExtensionPresent"), (uintptr_t)&alIsExtensionPresent);
  hook_addr(so_symbol(&conduit_mod, "alIsFilter"), (uintptr_t)&alIsFilter);
  hook_addr(so_symbol(&conduit_mod, "alIsSource"), (uintptr_t)&alIsSource);
  hook_addr(so_symbol(&conduit_mod, "alListener3f"), (uintptr_t)&alListener3f);
  hook_addr(so_symbol(&conduit_mod, "alListener3i"), (uintptr_t)&alListener3i);
  hook_addr(so_symbol(&conduit_mod, "alListenerf"), (uintptr_t)&alListenerf);
  hook_addr(so_symbol(&conduit_mod, "alListenerfv"), (uintptr_t)&alListenerfv);
  hook_addr(so_symbol(&conduit_mod, "alListeneri"), (uintptr_t)&alListeneri);
  hook_addr(so_symbol(&conduit_mod, "alListeneriv"), (uintptr_t)&alListeneriv);
  hook_addr(so_symbol(&conduit_mod, "alSource3f"), (uintptr_t)&alSource3f);
  hook_addr(so_symbol(&conduit_mod, "alSource3i"), (uintptr_t)&alSource3i);
  hook_addr(so_symbol(&conduit_mod, "alSourcePause"), (uintptr_t)&alSourcePause);
  hook_addr(so_symbol(&conduit_mod, "alSourcePausev"), (uintptr_t)&alSourcePausev);
  hook_addr(so_symbol(&conduit_mod, "alSourcePlay"), (uintptr_t)&alSourcePlay);
  hook_addr(so_symbol(&conduit_mod, "alSourcePlayv"), (uintptr_t)&alSourcePlayv);
  hook_addr(so_symbol(&conduit_mod, "alSourceQueueBuffers"), (uintptr_t)&alSourceQueueBuffers);
  hook_addr(so_symbol(&conduit_mod, "alSourceRewind"), (uintptr_t)&alSourceRewind);
  hook_addr(so_symbol(&conduit_mod, "alSourceRewindv"), (uintptr_t)&alSourceRewindv);
  hook_addr(so_symbol(&conduit_mod, "alSourceStop"), (uintptr_t)&alSourceStop);
  hook_addr(so_symbol(&conduit_mod, "alSourceStopv"), (uintptr_t)&alSourceStopv);
  hook_addr(so_symbol(&conduit_mod, "alSourceUnqueueBuffers"), (uintptr_t)&alSourceUnqueueBuffers);
  hook_addr(so_symbol(&conduit_mod, "alSourcef"), (uintptr_t)&alSourcef);
  hook_addr(so_symbol(&conduit_mod, "alSourcefv"), (uintptr_t)&alSourcefv);
  hook_addr(so_symbol(&conduit_mod, "alSourcei"), (uintptr_t)&alSourcei);
  hook_addr(so_symbol(&conduit_mod, "alSourceiv"), (uintptr_t)&alSourceiv);
  hook_addr(so_symbol(&conduit_mod, "alSpeedOfSound"), (uintptr_t)&alSpeedOfSound);
  hook_addr(so_symbol(&conduit_mod, "alcCaptureCloseDevice"), (uintptr_t)&alcCaptureCloseDevice);
  hook_addr(so_symbol(&conduit_mod, "alcCaptureOpenDevice"), (uintptr_t)&alcCaptureOpenDevice);
  hook_addr(so_symbol(&conduit_mod, "alcCaptureSamples"), (uintptr_t)&alcCaptureSamples);
  hook_addr(so_symbol(&conduit_mod, "alcCaptureStart"), (uintptr_t)&alcCaptureStart);
  hook_addr(so_symbol(&conduit_mod, "alcCaptureStop"), (uintptr_t)&alcCaptureStop);
  hook_addr(so_symbol(&conduit_mod, "alcCloseDevice"), (uintptr_t)&alcCloseDevice);
  hook_addr(so_symbol(&conduit_mod, "alcCreateContext"), (uintptr_t)&alcCreateContext);
  hook_addr(so_symbol(&conduit_mod, "alcDestroyContext"), (uintptr_t)&alcDestroyContext);
  hook_addr(so_symbol(&conduit_mod, "alcGetContextsDevice"), (uintptr_t)&alcGetContextsDevice);
  hook_addr(so_symbol(&conduit_mod, "alcGetCurrentContext"), (uintptr_t)&alcGetCurrentContext);
  hook_addr(so_symbol(&conduit_mod, "alcGetEnumValue"), (uintptr_t)&alcGetEnumValue);
  hook_addr(so_symbol(&conduit_mod, "alcGetError"), (uintptr_t)&alcGetError);
  hook_addr(so_symbol(&conduit_mod, "alcGetIntegerv"), (uintptr_t)&alcGetIntegerv);
  hook_addr(so_symbol(&conduit_mod, "alcGetString"), (uintptr_t)&alcGetString);
  hook_addr(so_symbol(&conduit_mod, "alcGetThreadContext"), (uintptr_t)&alcGetThreadContext);
  hook_addr(so_symbol(&conduit_mod, "alcIsExtensionPresent"), (uintptr_t)&alcIsExtensionPresent);
  hook_addr(so_symbol(&conduit_mod, "alcMakeContextCurrent"), (uintptr_t)&alcMakeContextCurrent);
  hook_addr(so_symbol(&conduit_mod, "alcOpenDevice"), (uintptr_t)&alcOpenDevice);
  hook_addr(so_symbol(&conduit_mod, "alcProcessContext"), (uintptr_t)&alcProcessContext);
  hook_addr(so_symbol(&conduit_mod, "alcSetThreadContext"), (uintptr_t)&alcSetThreadContext);
  hook_addr(so_symbol(&conduit_mod, "alcSuspendContext"), (uintptr_t)&alcSuspendContext);


  // hook_addr(so_symbol(&conduit_mod, "alAuxiliaryEffectSlotf"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alAuxiliaryEffectSlotfv"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alAuxiliaryEffectSloti"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alAuxiliaryEffectSlotiv"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alBuffer3f"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alBuffer3i"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alBufferData"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alBufferf"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alBufferfv"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alBufferi"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alBufferiv"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alDeleteAuxiliaryEffectSlots"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alDeleteBuffers"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alDeleteEffects"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alDeleteFilters"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alDeleteSources"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alDisable"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alDistanceModel"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alDopplerFactor"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alDopplerVelocity"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alEffectf"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alEffectfv"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alEffecti"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alEffectiv"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alEnable"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alFilterf"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alFilterfv"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alFilteri"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alFilteriv"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alGenAuxiliaryEffectSlots"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alGenBuffers"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alGenEffects"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alGenFilters"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alGenSources"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alGetAuxiliaryEffectSlotf"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alGetAuxiliaryEffectSlotfv"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alGetAuxiliaryEffectSloti"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alGetAuxiliaryEffectSlotiv"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alGetBoolean"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alGetBooleanv"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alGetBuffer3f"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alGetBuffer3i"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alGetBufferf"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alGetBufferfv"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alGetBufferi"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alGetBufferiv"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alGetDouble"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alGetDoublev"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alGetEffectf"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alGetEffectfv"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alGetEffecti"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alGetEffectiv"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alGetEnumValue"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alGetError"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alGetFilterf"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alGetFilterfv"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alGetFilteri"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alGetFilteriv"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alGetFloat"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alGetFloatv"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alGetInteger"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alGetIntegerv"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alGetListener3f"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alGetListener3i"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alGetListenerf"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alGetListenerfv"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alGetListeneri"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alGetListeneriv"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alGetProcAddress"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alGetSource3f"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alGetSource3i"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alGetSourcef"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alGetSourcefv"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alGetSourcei"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alGetSourceiv"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alGetString"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alIsAuxiliaryEffectSlot"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alIsBuffer"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alIsEffect"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alIsEnabled"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alIsExtensionPresent"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alIsFilter"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alIsSource"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alListener3f"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alListener3i"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alListenerf"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alListenerfv"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alListeneri"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alListeneriv"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alSource3f"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alSource3i"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alSourcePause"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alSourcePausev"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alSourcePlay"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alSourcePlayv"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alSourceQueueBuffers"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alSourceRewind"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alSourceRewindv"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alSourceStop"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alSourceStopv"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alSourceUnqueueBuffers"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alSourcef"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alSourcefv"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alSourcei"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alSourceiv"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alSpeedOfSound"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alcCaptureCloseDevice"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alcCaptureOpenDevice"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alcCaptureSamples"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alcCaptureStart"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alcCaptureStop"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alcCloseDevice"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alcCreateContext"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alcDestroyContext"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alcGetContextsDevice"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alcGetCurrentContext"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alcGetEnumValue"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alcGetError"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alcGetIntegerv"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alcGetString"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alcGetThreadContext"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alcIsExtensionPresent"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alcMakeContextCurrent"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alcOpenDevice"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alcProcessContext"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alcSetThreadContext"), ret0);
  // hook_addr(so_symbol(&conduit_mod, "alcSuspendContext"), ret0);
}
